
import AppLoader from "@/components/appLoader";
import "./globals.css";


export const metadata = {
  title: "mutolib-portfolio",
  description: "Generated by coder lord",
};



export default function RootLayout({ children }) {
  return (
    
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
         <AppLoader>
            {children}
         </AppLoader>
           
       
        </body>
      </html>
    
  )
}